[package]
name = "keylayout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.1.0"
itertools = "0.12.1"
rand = "0.8.5"
